FROM node:boron

#create app directory
WORKDIR ./

#install app dependencies
COPY package.json .
# for npm@5 or later, copy package-lock.json as well
# COPY package.json package-lock.json .

RUN npm install

#Bundle app source
COPY . .

EXPOSE 8080

CMD [ "npm","start" ]
